### ISSUE TITLE
It's hard to close application on Android

### ISSUE THREAD

**Issue by fizyk** [floydpink/Mantis-CI#2]
Right now application requires a lot of back-button clicks to go back pass the flash screen and exit it. One click usually gets back to flash screen, which then in turn redirects again to application main window.

It can be frustrating at times ;)

**Comment by floydpink** [comment]
Thank you for your kindness with a milder rating on the app store and for raising this as an issue here.

I have fixed this with the commit 9d9be85c2dc0aaefada4dcc644988a5e8ffa6bfd. It would be awesome if you could kindly get the update and test this for me.

Have a great day !
